### ISSUE TITLE
Is this a conflict in word-initial hard sign removal and capitalization?

### ISSUE THREAD

**Issue by rueter** [giellalt/lang-mdf#1]
Symptoms: the upper-case _Рьвя_ 'wife' is not recognized by the tokenizer, but the lower-case _рьвя_ is.

The Moksha language traditionally does not show schwa vowels in the first syllable in the normal orthography.
The dictionary presentation, however, shows them. Conversion to the standard orthography is made possible with the following regex: 
lang-mdf/src/filters/remove-hard-sign-in-first-syllable.regex

There is a small handful of words -- mainly ones derived from the stems ```ърдаз``` 'dirt' and ```ърьвя``` 'wife' which actually begin with a schwa.

These words are not recognized by the analyzer.
<img width="643" alt="mdf_word-initial_schwa_vs_capitalization_2023-03-19" src="https://user-images.githubusercontent.com/14276164/226200723-b7175b2a-57c4-4954-815f-263aaef225c4.png">

**Comment by flammie** [comment]
I think the uppercasing rules atm are defined like `р (->) Р || .#. _ ;` s.t. they mayn't match `ь:0 р` or so if that's how it goes through the lexc and twol? Haven't tested just guessing

**Comment by rueter** [comment]
This appears to work well.
